[package]
name = "ok"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_list_allocator = "0.10.6"
wasmi = { version = "1.0.9", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
limine = "0.6.3"
x86_64 = "0.15.4"
x86 = "0.52.0"
spin = "0.10.0"

[profile.release]
strip = true
lto = true
opt-level = "s"

[[bin]]
name = "ok"
path = "src/main.rs"
test = false
bench = false
